# Generated by Django 4.2 on 2026-08-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnHubModule',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('badge', models.CharField(default='INTERACTIVE AI GUIDE', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('sourceFile', models.JSONField(blank=True, default=dict, null=True)),
                ('sourceFiles', models.JSONField(blank=True, default=list)),
                ('slides', models.JSONField(blank=True, default=list)),
                ('paragraphs', models.JSONField(blank=True, default=list)),
                ('bottomTags', models.JSONField(blank=True, default=list)),
                ('isPublished', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learnhub_modules', to='api.batch')),
            ],
        ),
        migrations.CreateModel(
            name='LearnHubStudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completedSlides', models.JSONField(blank=True, default=list)),
                ('masteredTags', models.JSONField(blank=True, default=list)),
                ('quizScores', models.JSONField(blank=True, default=dict)),
                ('lastAccessedAt', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='api.learnhubmodule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnhub_progress', to='api.student')),
            ],
            options={
                'unique_together': {('student', 'module')},
            },
        ),
    ]
