# Generated by Django 4.2 on 2026-08-20 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_learnhubmodule_learnhubstudentprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveQuestion',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('type', models.CharField(default='mcq', max_length=50)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correctAnswer', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isClosed', models.BooleanField(default=False)),
                ('timeLimitSeconds', models.IntegerField(default=30)),
                ('points', models.IntegerField(default=100)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('quizTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('askedByStudentName', models.CharField(blank=True, max_length=255, null=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('upvotedStudentIds', models.JSONField(blank=True, default=list)),
                ('answerByInstructor', models.TextField(blank=True, null=True)),
                ('isAnswered', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('askedByStudent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asked_questions', to='api.student')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_questions', to='api.batch')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='LiveQAResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=255)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('answer', models.TextField()),
                ('isCorrect', models.BooleanField(blank=True, null=True)),
                ('responseTimeMs', models.IntegerField(default=0)),
                ('submittedAt', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.livequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_responses', to='api.student')),
            ],
            options={
                'ordering': ['submittedAt'],
                'unique_together': {('question', 'student')},
            },
        ),
    ]
