# Generated by Django 4.2 on 2026-08-20 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_livequestion_liveqaresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(default='mixed', max_length=50)),
                ('durationMinutes', models.IntegerField(default=30)),
                ('totalPoints', models.IntegerField(default=100)),
                ('isPublished', models.BooleanField(default=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.batch')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=255)),
                ('submittedAt', models.DateTimeField(auto_now=True)),
                ('startedAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='submitted', max_length=50)),
                ('timeLeftSeconds', models.IntegerField(default=0)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('codeSubmissions', models.JSONField(blank=True, default=dict)),
                ('questionScores', models.JSONField(blank=True, default=dict)),
                ('score', models.FloatField(default=0)),
                ('maxScore', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('autoGraded', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='api.student')),
            ],
            options={
                'ordering': ['-submittedAt'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
