# Generated by Django 5.2.17 on 2026-08-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(default='CERTIFICATE OF EXCELLENCE', max_length=255)),
                ('subtitle', models.CharField(default='MIND2I ARTIFICIAL INTELLIGENCE INSTITUTE', max_length=255)),
                ('issuerName', models.CharField(default='MIND2I ARTIFICIAL INTELLIGENCE INSTITUTE', max_length=255)),
                ('signatories', models.JSONField(blank=True, default=list)),
                ('descriptionText', models.TextField(blank=True, default='')),
                ('isUnlocked', models.BooleanField(default=True)),
                ('templateStyle', models.CharField(default='modern', max_length=50)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='api.batch')),
            ],
            options={
                'ordering': ['-updatedAt'],
            },
        ),
    ]
