# Generated by Django 4.2 on 2026-08-22 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_certificatetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='mind2i@admin', max_length=255)),
                ('role', models.CharField(default='instructor', max_length=50)),
                ('assignedBatches', models.JSONField(blank=True, default=list)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='AppSettingsModel',
            fields=[
                ('id', models.CharField(default='global', max_length=100, primary_key=True, serialize=False)),
                ('enableCodingIDE', models.BooleanField(default=True)),
                ('enableQuiz', models.BooleanField(default=True)),
                ('enableLearnHub', models.BooleanField(default=True)),
                ('enableCertificate', models.BooleanField(default=True)),
                ('enableMyReport', models.BooleanField(default=True)),
                ('enableLiveQA', models.BooleanField(default=True)),
                ('enableLeaderboard', models.BooleanField(default=True)),
                ('enablePeerReview', models.BooleanField(default=False)),
                ('enableTelemetryAnalytics', models.BooleanField(default=True)),
                ('enableZoomSync', models.BooleanField(default=True)),
                ('defaultStudentPassword', models.CharField(default='student123', max_length=255)),
                ('zoomConfig', models.JSONField(blank=True, default=dict)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_settings', to='api.batch')),
            ],
            options={
                'ordering': ['-updatedAt'],
            },
        ),
    ]
