# Generated by Django 4.2 on 2026-08-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_adminuser_appsettingsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='livequestion',
            name='isLocked',
            field=models.BooleanField(default=False),
        ),
    ]
