# Generated by Django 4.2 on 2026-08-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_livequestion_islocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='isLocked',
            field=models.BooleanField(default=False),
        ),
    ]
