# Generated by Django 4.2 on 2026-08-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_assignment_islocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='zoomConfig',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='zoomLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
