# Generated by Django 4.2 on 2026-08-27 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_batch_zoomconfig_batch_zoomlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsettingsmodel',
            options={},
        ),
        migrations.CreateModel(
            name='ScheduledMeeting',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('agenda', models.TextField(blank=True, default='')),
                ('instructorName', models.CharField(default='Dr. Vikram Aditya & MINDA2 Team', max_length=255)),
                ('scheduledDate', models.CharField(default='Today', max_length=100)),
                ('scheduledTime', models.CharField(default='10:00 AM - 01:00 PM', max_length=100)),
                ('meetingLink', models.CharField(blank=True, default='', max_length=500)),
                ('meetingId', models.CharField(blank=True, default='', max_length=100)),
                ('passcode', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='scheduled', max_length=50)),
                ('recordingUrl', models.CharField(blank=True, default='', max_length=500)),
                ('isRecordingUnlocked', models.BooleanField(default=True)),
                ('isPublished', models.BooleanField(default=True)),
                ('orderIndex', models.IntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meetings', to='api.batch')),
            ],
            options={
                'ordering': ['orderIndex', 'createdAt'],
            },
        ),
    ]
