# Generated by Django 4.2 on 2026-08-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_appsettingsmodel_options_scheduledmeeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='instructorName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='scheduledDate',
            field=models.CharField(blank=True, default='Today', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='scheduledTime',
            field=models.CharField(blank=True, default='10:00 AM - 01:00 PM', max_length=100),
        ),
    ]
