# Generated by Django 4.2 on 2026-09-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_scheduledmeeting_instructorname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveqaresponse',
            name='aiFeedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveqaresponse',
            name='instructorReply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveqaresponse',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveqaresponse',
            name='reviewedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveqaresponse',
            name='reviewer',
            field=models.CharField(blank=True, default='none', max_length=50, null=True),
        ),
    ]
