# Generated by Django 4.2 on 2026-09-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_liveqaresponse_aifeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettingsmodel',
            name='enableStudentReviews',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='trainerRating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='trainerReview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='trainerReviewedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
