# Generated by Django 4.2 on 2026-09-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_appsettingsmodel_enablestudentreviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aiVerdictEvaluatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='aiVerdictImprovements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='aiVerdictRating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='aiVerdictStrengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='aiVerdictSummary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
