# Generated by Django 4.2 on 2026-09-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_student_aiverdictevaluatedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='endDate',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='assignment',
            name='endTime',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='assignment',
            name='startDate',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='assignment',
            name='startTime',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
