# Generated by Django 4.2 on 2026-09-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_assignment_enddate_assignment_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livequestion',
            name='launchedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
