# Generated by Django 4.2 on 2026-09-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_livequestion_launchedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='isLocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='collegeRegNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
